import NavBar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pokedex',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-300'>
        <NavBar />
        {children}</body>
    </html>
  )
}


// git remote add pokedex-nextjs https://github.com/Gaurav8595/pokedex-nextjs.git
